/**
 * Created by root on 16-9-27.
 */
export const LOGIN = 'LOGIN';
export const ROUTE_PLANNER_INIT = 'ROUTE_PLANNER_INIT';
export const ROUTE_PLANNER_SELECT_ORIGIN = 'ROUTE_PLANNER_SELECT_ORIGIN';
export const ROUTE_PLANNER_SELECT_DESTINATION = 'ROUTE_PLANNER_SELECT_DESTINATION';
export const ROUTE_PLANNER_SELECT_WAYPOINT = 'ROUTE_PLANNER_SELECT_WAYPOINT';
export const LOCATION_LIST_LOADING = 'LOCATION_LIST_LOADING';
export const LOCATION_LIST_LOADED = 'LOCATION_LIST_LOADED';
export const LOCATION_INFO_LOADING = 'LOCATION_INFO_LOADING';
export const LOCATION_INFO_LOADED = 'LOCATION_INFO_LOADED';
export const CHARGER_LIST_LOADED = 'CHARGER_LIST_LOADED';
export const CHARGER_LIST_LOADING = 'CHARGER_LIST_LOADING';
export const ROUTE_INIT = 'ROUTE_INIT';
export const ROUTE_LOADING = 'ROUTE_LOADING';
export const ROUTE_LOADED = 'ROUTE_LOADED';

export const MAP_INIT = 'MAP_INIT';
export const MAP_LOADING = 'MAP_LOADING';
export const MAP_LOADED = 'MAP_LOADED';